### PR TITLE
Speedup and robustness improvements

### PR DESCRIPTION
**Pull request by einar90**
The `collect_intersected_cells` method has been refactored, and core parts have been rewritten in order  to make it faster and more robust. In particular, 

* moving segment end-points that are initially outside the reservoir into it is now significantly faster.
* the issue of cycling when traversing the segment to find new new cells has been fixed.
* whether or not a cell is active is now properly considered when moving end-points and when traversing the segment.
* The assert that caused the program to terminate if the expected final cell does not match the final cell found when traversing has been replaced with a check that prints a warning and clears the list of intersected cells. This change this lets us handle this in the other parts of FieldOpt instead of it just crashing.

More throrough descriptions can be found in the primary commits that introduced the changes:

* 5eaddfd Speeding up the moving of end-points.
* e9cf0b5 Fix cycling

The new implementation has been tested with well paths from both the 5spot model and the Norne model that were found to be problematic. @Bellout will run some more thorough tests.

### CODE REVIEW

**Comment by agchitu** [comment]
Hi Einar, 

I am looking at the code and redo some of the tests we have here. The first tests seem to work fine but I want to be sure. Looking at the commits' history there was quite some struggle :).  I'll work more on Friday and most probably have a more complete image by then. Have a nice king's day!

**Comment by einar90** [comment]
Hi Alin,

There were quite a lot of struggles, yes! Every problem I fixed uncovered a new problem that was previously hidden by other problems. But I expected that, that's usually how it goes with non-trivial programming :) 

I agree that the slight differences are probably from slightly different intersection points. I believe this is mainly because the step lengths are slightly larger now than they used to be; changing the epsions [here](https://github.com/PetroleumCyberneticsGroup/FieldOpt-WellIndexCalculator/pull/14/files#diff-9f7fdc1d58b560dbcc88544ec891e73fR153) and [here](https://github.com/PetroleumCyberneticsGroup/FieldOpt-WellIndexCalculator/pull/14/files#diff-9f7fdc1d58b560dbcc88544ec891e73fR289) should (hopefully) bring the results closer to the old ones, at the cost of some performace.

I believe @Bellout will also be running some more thorough tests today.

**Comment by einar90** [comment]
Great to hear that it's working! I will merge it as soon as Mathias has finished his tests, so most likely early next week. As to your comments:

1. Are these changes significant, i.e. large enough to impact the results of simulations?
2. I agree on both points. I want to implement a verbose switch to show/hide the prints,  and implementing write-to-file is easy enough. We can do that in the next version.

**Comment by einar90** [comment]
An update on the tests from @Bellout : The new implementation has a consistent 1% error when compared to RMS for the 5spot model. This is because the step lengths are longer now, so the part of the segment that passes through the cells when we get to the calculation is slightly shorter.

This is largely remedied by reducing the divisor for the epsilon declarations (mentioned in a previous comment here), but this also causes the calculation to take a lot longer: changing the divisors from 100  and 10 to 1000 in `collect_intersected_cells` and `findEndpoint`, respectively, brings the accuracy to approximately the same level as the old implementation, but our tests for complicated well paths take approximately 3 times longer to finish.

I propose adding a switch (high/low accuracy mode) in a future pull request. I'll add a task on this in the Project page here on GitHub, which I propose we start using for the WIC repo to keep track of what people are working on (to avoid conflicts and double-work).

**Pull request merged**
