### PR TITLE
Well Index Calculation for segmented wells

### PR DESCRIPTION
**Pull request by agchitu**
This version extends calculation of well index to segmented wells. 
A well is defined as a list of well segments each segment being defined by its heel, toe and radius.

The main application will accept the argument --well-filedef <path_to_file> and load the well definition from the file. This is an ASCII file with one segment defined  per line: well_name hx hy hz tx ty tz radius
Well_name	995.00	995.00	2500.00	995.00	995.00	2600.00	0.076200
Well_name	994.92	995.00	2533.00	895.00	995.00	2533.00	0.025400
It is possible to define multiple wells in the same file.

A new argument --debug is allowed. The tool will print in the file debug.dat all projection related data (lx, ly, lz, permx, .....)

The path to the grid file is required.
 
Searching for intersected grid block will be restricted to a bounding box defined around the heel  and toe. This is done as a simple first try to speed up this process.

(disclaimer: some family related issues made working this rather discontinuous - this is also the reason I am dumping so many commits in one pull request)

### CODE REVIEW

**Comment by einar90** [comment]
This looks great, good work! I wont have time to look thoroughly at this (or merge it) until early January because of a course I have to finish.

But I would like some unit tests (in the `./tests` directory) for the new non-trivial methods in the `IntersectedCell` class. If you're not familiar with the Google C++ testing framework, there's a primer [here](https://github.com/google/googletest/blob/master/googletest/docs/Primer.md). If you don't want to spend time doing this that's okay too, just add some comments in the header file (or list it in a comment here), stating the expected input and output for the functions, and I'll take care of writing the tests.

**Comment by agchitu** [comment]
Hi,

I just came back from holiday. I will talk with colleagues and plan some more work on this subject for the next weeks. I'll come back.

**Comment by einar90** [comment]
Hi,
I finally got around to actually testing this, sorry for the delay. 
It wont build for me because you're using a `GetBoundingBoxCellIndices()`, as well as some other methods in the `Grid` class. I assume this is some stuff you've added to the class yourself. Can you please create a pull request for this too?

**Comment by agchitu** [comment]
Adjusted the unit test code to build with the new library. The code is building but I have not yet run the tests, will do that soon.

**Comment by agchitu** [comment]
Hi Einar,

I am still working on an improvement of this code, though on a very irregular basis. Are you still looking at this PR? Anyway, next week I am on holiday but after my return I'll have new commits.

**Comment by einar90** [comment]
Hi Alin,

Yes, I'm still looking at this. Looking forward to having it integrated!

I've made a couple of adjustments to the Reservoir code today (PR is going up in 5 minutes). These changes allows us to use grids that include inactive cells without crashing, and they also include some optimizations w.r.t. performance, one of which is relevant for you: the properties from the `.INIT` file are no longer retrieved when `GetCell()`  is called, only the cell geometry is (this was mainly done because ERT crashes if we tried to get porosity for an inactive cell). Porosity and permeability is now retrieved by calling `Grid::FillCellProperties(&cell)`. I've already made this change in the current WIC version: it's only one extra line. Note that the performance gain is only a side effect, the main intention was to fix a bug.

**Comment by agchitu** [comment]
Hi Einar,

Thanks for your message. I have found that bug as well and got it fix, but from what you write I took a different approach. These last two weeks I spent a bit more time on the tool and work for improving the performance (processing speed) and make it more robust for inactive cells and out of the reservoir well segments. Let's try to align the codes upon my return in March. Cheers, Alin

**Pull request closed without merging**
